[package]
name = "piky"
version = "0.1.0"
authors = ["Antonin Rouxel"]
edition = "2024"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_8"] }
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
gtk = { version = "0.11.4", package = "gtk4", features = ["gnome_50"] }
merman-core = "0.7.0"
merman-render = "0.7.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
