[package]
name = "piky"
version = "0.1.0"
authors = ["Antonin Rouxel"]
edition = "2024"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_5"] }
cairo = { version = "0.22.0", package = "cairo-rs", default-features = false, features = ["use_glib", "png"] }
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
gtk = { version = "0.11.4", package = "gtk4", features = ["gnome_46"] }
merman-core = "0.8.0-alpha.3"
merman-render = "0.8.0-alpha.3"
serde_json = "1"
tiny-skia-path = "0.12"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
usvg = "0.48.1"
